//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delegacao : EntidadeDB, IEntidadeDBCore
    {
    	
        public int IdDelegacao { get; set; }
    	
        public string LoginDe { get; set; }
    	
        public string NomeDe { get; set; }
    	
        public string EmailDe { get; set; }
    	
        public string LoginPara { get; set; }
    	
        public string NomePara { get; set; }
    	
        public string EmailPara { get; set; }
    	
        public System.DateTime DataInicio { get; set; }
    	
        public System.DateTime DataFim { get; set; }
    	
        public int Status { get; set; }
    	
        public string LoginInclusao { get; set; }
    	
        public System.DateTime DataInclusao { get; set; }
    	
        public string LoginAlteracao { get; set; }
    	
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    	
        public bool Ativo { get; set; }
    	
        public Nullable<int> CodigoDelegacao2007 { get; set; }
    }
}
