//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAttachment : EntidadeDB, IEntidadeDBCore
    {
    	
        public int IdEmailAttachment { get; set; }
    	
        public byte TipoEmail { get; set; }
    	
        public bool Processado { get; set; }
    	
        public System.Guid CodigoLista { get; set; }
    	
        public int IdItem { get; set; }
    	
        public string NomeProposta { get; set; }
    	
        public string Ibm { get; set; }
    	
        public string RazaoSocial { get; set; }
    	
        public string GerenteTerritorio { get; set; }
    	
        public string GerenteRegiao { get; set; }
    	
        public string DiretorVendas { get; set; }
    	
        public string Cdr { get; set; }
    	
        public string Gdr { get; set; }
    	
        public bool Ambiente2013 { get; set; }
    	
        public string DescricaoAssuntoEmail { get; set; }
    	
        public string DescricaoMensagemEmail { get; set; }
    	
        public string EmailUsuario { get; set; }
    	
        public string LoginInclusao { get; set; }
    	
        public string LoginAlteracao { get; set; }
    	
        public System.DateTime DataInclusao { get; set; }
    	
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    	
        public bool Ativo { get; set; }
    }
}
