//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado : EntidadeDB, IEntidadeDBCore
    {
        public Estado()
        {
            this.Cidade = new HashSet<Cidade>();
        }
    
    	
        public int Id { get; set; }
    	
        public string Nome { get; set; }
    	
        public string UF { get; set; }
    
        public virtual ICollection<Cidade> Cidade { get; set; }
    }
}
