//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lista : EntidadeDB, IEntidadeDBCore
    {
        public Lista()
        {
            this.ListaHist = new HashSet<ListaHist>();
            this.InstanciaFluxo = new HashSet<InstanciaFluxo>();
        }
    
    	
        public System.Guid CodigoLista { get; set; }
    	
        public string Nome { get; set; }
    	
        public string DescricaoUrlLista { get; set; }
    	
        public string DescricaoUrlItem { get; set; }
    	
        public string DescricaoUrlTarefa { get; set; }
    	
        public bool Ambiente2007 { get; set; }
    
        public virtual ICollection<ListaHist> ListaHist { get; set; }
        public virtual ICollection<InstanciaFluxo> InstanciaFluxo { get; set; }
    }
}
