//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogIntegracao : EntidadeDB, IEntidadeDBCore
    {
    	
        public long IdLogIntegracao { get; set; }
    	
        public System.DateTime DataExecucao { get; set; }
    	
        public int WorkflowProgressID { get; set; }
    	
        public int QuantidadeLista { get; set; }
    	
        public int QuantidadeInstancia { get; set; }
    	
        public int QuantidadeTarefa { get; set; }
    	
        public int QuantidadeDelegacao { get; set; }
    	
        public int TempoExecucao { get; set; }
    	
        public Nullable<bool> ExecucaoCompleta { get; set; }
    	
        public Nullable<bool> ExecucaoGestaoFluxo { get; set; }
    	
        public Nullable<int> QuantidadeGestaoFluxoFluxo { get; set; }
    	
        public Nullable<int> QuantidadeGestaoFluxoTarefa { get; set; }
    	
        public Nullable<int> QuantidadeGestaoFluxoTarefaStatus { get; set; }
    }
}
