//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalDeFluxoEntities : DbContext
    {
        public PortalDeFluxoEntities()
            : base("name=PortalDeFluxoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Delegacao> Delegacao { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<EmailAttachment> EmailAttachment { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<EstruturaComercial> EstruturaComercial { get; set; }
        public virtual DbSet<EstruturaComercial_Modificada> EstruturaComercial_Modificada { get; set; }
        public virtual DbSet<EstruturaComercial_Salesforce> EstruturaComercial_Salesforce { get; set; }
        public virtual DbSet<HorarioVerao> HorarioVerao { get; set; }
        public virtual DbSet<ListaHist> ListaHist { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<LogIntegracao> LogIntegracao { get; set; }
        public virtual DbSet<Parametro> Parametro { get; set; }
        public virtual DbSet<PropostaDocumento> PropostaDocumento { get; set; }
        public virtual DbSet<ServicoAgendado> ServicoAgendado { get; set; }
        public virtual DbSet<TabelaExemplo> TabelaExemplo { get; set; }
        public virtual DbSet<TarefaHist> TarefaHist { get; set; }
        public virtual DbSet<TipoProposta> TipoProposta { get; set; }
        public virtual DbSet<TipoPropostaDocumento> TipoPropostaDocumento { get; set; }
        public virtual DbSet<WFGestaoFluxo_Fluxo> WFGestaoFluxo_Fluxo { get; set; }
        public virtual DbSet<WFGestaoFluxo_Tarefa> WFGestaoFluxo_Tarefa { get; set; }
        public virtual DbSet<Lista> Lista { get; set; }
        public virtual DbSet<AnoContratual> AnoContratual { get; set; }
        public virtual DbSet<Lembrete> Lembrete { get; set; }
        public virtual DbSet<Tarefa> Tarefa { get; set; }
        public virtual DbSet<RelatorioOperacionalTarefa> RelatorioOperacionalTarefa { get; set; }
        public virtual DbSet<InstanciaFluxo> InstanciaFluxo { get; set; }
        public virtual DbSet<GrupoSP> GrupoSP { get; set; }
        public virtual DbSet<GrupoUsuariosSP> GrupoUsuariosSP { get; set; }
        public virtual DbSet<UsuarioSP> UsuarioSP { get; set; }
        public virtual DbSet<SAEParametros> SAEParametros { get; set; }
    }
}
