//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatorioOperacionalTarefa : EntidadeDB, IEntidadeDBCore
    {
    	
        public string Fluxo { get; set; }
    	
        public string Tabela { get; set; }
    	
        public string IdTipoProposta { get; set; }
    	
        public string IdProposta { get; set; }
    	
        public string TituloProposta { get; set; }
    	
        public string Combo { get; set; }
    	
        public string RazaoSocial { get; set; }
    	
        public string IBM { get; set; }
    	
        public string SiteCode { get; set; }
    	
        public string GT { get; set; }
    	
        public string GR { get; set; }
    	
        public string Diretor { get; set; }
    	
        public string CDR { get; set; }
    	
        public string GDR { get; set; }
    	
        public string CodigoLista { get; set; }
    }
}
