//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarefaHist : EntidadeDB, IEntidadeDBCore
    {
    	
        public int IdTarefaHist { get; set; }
    	
        public int IdTarefa { get; set; }
    	
        public byte TipoTarefaHist { get; set; }
    	
        public string LoginDe { get; set; }
    	
        public string LoginPara { get; set; }
    	
        public string LoginInclusao { get; set; }
    	
        public System.DateTime DataInclusao { get; set; }
    	
        public string LoginAlteracao { get; set; }
    	
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    	
        public bool Ativo { get; set; }
    	
        public string ComentarioDelegacao { get; set; }
    
        public virtual Tarefa Tarefa { get; set; }
    }
}
