//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa : EntidadeDB, IEntidadeDBCore
    {
        public Tarefa()
        {
            this.Lembrete = new HashSet<Lembrete>();
            this.Tarefa1 = new HashSet<Tarefa>();
            this.TarefaHist = new HashSet<TarefaHist>();
        }
    
    	
        public int IdTarefa { get; set; }
    	
        public int IdInstanciaFluxo { get; set; }
    	
        public Nullable<System.Guid> CodigoTarefa { get; set; }
    	
        public Nullable<int> CodigoConfiguracao { get; set; }
    	
        public Nullable<int> AprovacaoPor { get; set; }
    	
        public string NomeTarefa { get; set; }
    	
        public string NomeEtapa { get; set; }
    	
        public Nullable<byte> TipoTarefa { get; set; }
    	
        public string DescricaoAreaResponsavel { get; set; }
    	
        public string EmailResponsavel { get; set; }
    	
        public string LoginResponsavel { get; set; }
    	
        public string NomeResponsavel { get; set; }
    	
        public string EmailSuperior { get; set; }
    	
        public string LoginSuperior { get; set; }
    	
        public string NomeSuperior { get; set; }
    	
        public Nullable<int> SLA { get; set; }
    	
        public Nullable<System.DateTime> DataSLA { get; set; }
    	
        public Nullable<System.DateTime> DataEscalonamento { get; set; }
    	
        public string ComentarioAprovacao { get; set; }
    	
        public string DescricaoAcaoEfetuada { get; set; }
    	
        public string DescricaoAcao { get; set; }
    	
        public string DescricaoAssuntoEmail { get; set; }
    	
        public string DescricaoMensagemEmail { get; set; }
    	
        public string DescricaoAssuntoEmailEscalonamento { get; set; }
    	
        public string DescricaoMensagemEmailEscalonamento { get; set; }
    	
        public bool CopiarSuperior { get; set; }
    	
        public bool EmailEnviado { get; set; }
    	
        public bool TarefaCompleta { get; set; }
    	
        public bool TarefaEscalonada { get; set; }
    	
        public string NomeCompletadoPor { get; set; }
    	
        public string LoginCompletadoPor { get; set; }
    	
        public Nullable<System.DateTime> DataFinalizado { get; set; }
    	
        public System.DateTime DataAtribuido { get; set; }
    	
        public string LoginInclusao { get; set; }
    	
        public string LoginAlteracao { get; set; }
    	
        public System.DateTime DataInclusao { get; set; }
    	
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    	
        public bool Ativo { get; set; }
    	
        public Nullable<int> CodigoTarefaSP { get; set; }
    	
        public Nullable<System.Guid> CodigoListaTarefa { get; set; }
    	
        public Nullable<int> CodigoHumanWorkflowID { get; set; }
    	
        public string DescricaoAcaoFinalizarEtapa { get; set; }
    	
        public Nullable<bool> AprovadoPorEmail { get; set; }
    	
        public Nullable<int> IndexAprovacao { get; set; }
    	
        public Nullable<bool> AprovacoesAtuais { get; set; }
    	
        public Nullable<int> IdTarefaPai { get; set; }
    	
        public Nullable<bool> EnviarPdf { get; set; }
    	
        public Nullable<int> IndexHeadLineFinal { get; set; }
    	
        public string ParametrosUrl { get; set; }
    	
        public Nullable<bool> AprovacaoAutomatica { get; set; }
    	
        public string DescricaoRespostaAutomatica { get; set; }
    	
        public Nullable<bool> AprovadoAutomaticamente { get; set; }
    	
        public string ComentarioAprovacaoAutomatica { get; set; }
    
        public virtual ICollection<Lembrete> Lembrete { get; set; }
        public virtual ICollection<Tarefa> Tarefa1 { get; set; }
        public virtual Tarefa Tarefa2 { get; set; }
        public virtual ICollection<TarefaHist> TarefaHist { get; set; }
        public virtual InstanciaFluxo InstanciaFluxo { get; set; }
    }
}
