//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFGestaoFluxo_Tarefa : EntidadeDB, IEntidadeDBCore
    {
    	
        public int CD_TAREFA { get; set; }
    	
        public int CD_FLUXO { get; set; }
    	
        public System.Guid CD_WORKFLOW_ID { get; set; }
    	
        public System.Guid CD_LISTA_TAREFA { get; set; }
    	
        public int NR_ESTADO_ID { get; set; }
    	
        public int NR_ACAO_ID { get; set; }
    	
        public int NR_ESTADO_ACAO_ID { get; set; }
    	
        public bool SN_FLUXO_ATUAL { get; set; }
    	
        public string NM_TAREFA { get; set; }
    	
        public string NM_PAPEL { get; set; }
    	
        public string NM_RESPONSAVEL { get; set; }
    	
        public string NM_RESPONSAVEL_ORIGINAL { get; set; }
    	
        public string NM_RESPONSAVEL_LOGIN { get; set; }
    	
        public string NM_RESPONSAVEL_LOGIN_ORIGINAL { get; set; }
    	
        public string NM_SUPERVISORES { get; set; }
    	
        public string NM_SUPERVISORES_LOGIN { get; set; }
    	
        public string NM_STATUS { get; set; }
    	
        public string NM_COMENTARIOS { get; set; }
    	
        public Nullable<bool> SN_DELEGADO_SUPERVISOR { get; set; }
    	
        public Nullable<int> NR_EMAIL_SUPERVISOR { get; set; }
    	
        public Nullable<int> NR_EMAIL_RESPONSAVEL { get; set; }
    	
        public Nullable<int> NR_SLA_ESPERADO { get; set; }
    	
        public Nullable<int> NR_SLA_REAL { get; set; }
    	
        public Nullable<System.DateTime> DT_SLA { get; set; }
    	
        public Nullable<System.DateTime> DT_SAIDA { get; set; }
    	
        public Nullable<System.DateTime> DT_CRIACAO { get; set; }
    	
        public Nullable<System.DateTime> DT_MODIFICACAO { get; set; }
    	
        public Nullable<System.DateTime> DT_DELEGACAO_PROGRAMADA { get; set; }
    	
        public Nullable<int> CD_ITEM_TAREFA { get; set; }
    }
}
