
//------------------------------------------------------------------------------
// <auto-generated>
// Código Gerado via T4
//
// Não alterar o código - As informações serão perdidadas.
// </auto-generated>
//------------------------------------------------------------------------------
using PortalDeFluxos.Core.BLL.Atributos;
using System;
using System.Collections.Generic;
using Iteris;


namespace PortalDeFluxos.Core.BLL.Modelo
{
		
	[InternalName("Cadastro de Grupos")]
	public class ListaSP_CadastroDeGrupos : EntidadeSP
	{
		[InternalName("Grupo")]
		public Grupo Grupo { get; set; }

		[InternalName("Superior")]
		public Usuario Superior { get; set; }

	}
		
	[InternalName("Raizen UserControl")]
	public class ListaSP_RaizenUserControl : EntidadeSP
	{
		[InternalName("TipoUserControl")]
		public String TipoUserControl { get; set; }

		[InternalName("urlUserControl")]
		public String UrlUserControl { get; set; }

	}
		
	[InternalName("Feriados")]
	public class ListaSP_Feriados : EntidadeSP
	{
		[InternalName("Data")]
		public DateTime Data { get; set; }

	}
		
	[InternalName("Fluxos")]
	public class ListaSP_Fluxos : EntidadeSP
	{
	}
		
	[InternalName("Raízen - Aprovadores")]
	public class ListaSP_RaizenAprovadores : EntidadeSP
	{
		[InternalName("Responsavel")]
		public Usuario Responsavel { get; set; }

		[InternalName("Grupo")]
		public Grupo Grupo { get; set; }

		[InternalName("Gerencias")]
		public List<Usuario> Gerencias { get; set; }

	}
		
	[InternalName("Raízen - Configurações de Fluxo")]
	public class ListaSP_RaizenConfiguracoesDeFluxo : EntidadeSP
	{
		[InternalName("NomeTarefa")]
		public String NomeDaTarefa { get; set; }

		[InternalName("CCSuperior")]
		public Boolean? CopiarSuperior { get; set; }

		[InternalName("Saidas")]
		public String[] Saidas { get; set; }

		[InternalName("TipoAprovacao")]
		public String TipoDeAprovacao { get; set; }

		[InternalName("Expediente")]
		public String Expediente { get; set; }

		[InternalName("DiasUteis")]
		public String[] DiasUteis { get; set; }

		[InternalName("SLA")]
		public Int32 SLA { get; set; }

		[InternalName("AprovacaoPor")]
		public String AprovacaoPor { get; set; }

		[InternalName("Fluxo")]
		public ListaSP_Fluxos Fluxo { get; set; }

		[InternalName("ResponsavelTipoItem")]
		public String ResponsavelDoTipoItem { get; set; }

		[InternalName("SuperiorTipoItem")]
		public String SuperiorDoTipoItem { get; set; }

		[InternalName("SaidaFinalizarEtapa")]
		public String[] SaidaFinalizarEtapa { get; set; }

		[InternalName("Grupo")]
		public Grupo Grupo { get; set; }

		[InternalName("TemplateEmail")]
		public ListaSP_RaizenTemplateDeEmails TemplateDeEmail { get; set; }

		[InternalName("Lembretes")]
		public List<ListaSP_RaizenLembretes> Lembretes { get; set; }

		[InternalName("CampoHeadlineSize")]
		public String CampoHeadlineSize { get; set; }

		[InternalName("Obrigatoria")]
		public Boolean? Obrigatoria { get; set; }

		[InternalName("SlaRecorrente")]
		public Boolean? SLARecorrente { get; set; }

		[InternalName("NomeEtapa")]
		public String NomeEtapa { get; set; }

		[InternalName("AprovacaoEmail")]
		public Boolean? AprovacaoEmail { get; set; }

		[InternalName("AprovacaoAutomatica")]
		public Boolean? AprovacaoAutomatica { get; set; }

		[InternalName("RespostaAutomatica")]
		public String RespostaAutomatica { get; set; }

		[InternalName("ComentarioAprovacaoAutomatica")]
		public String ComentarioDaAprovacaoAutomatica { get; set; }

	}
		
	[InternalName("Raízen - Lembretes")]
	public class ListaSP_RaizenLembretes : EntidadeSP
	{
		[InternalName("NumeroRepeticoes")]
		public Int32 NumeroDeRepeticoes { get; set; }

		[InternalName("Dias")]
		public Int32? Dias { get; set; }

		[InternalName("Horas")]
		public Int32? Horas { get; set; }

		[InternalName("Minutos")]
		public Int32? Minutos { get; set; }

		[InternalName("CCSuperior")]
		public Boolean? CCSuperior { get; set; }

		[InternalName("TemplateEmail")]
		public ListaSP_RaizenTemplateDeEmails TemplateDeEmail { get; set; }

	}
		
	[InternalName("Raízen - Template de E-mails")]
	public class ListaSP_RaizenTemplateDeEmails : EntidadeSP
	{
		[InternalName("AssuntoEmail")]
		public String Assunto { get; set; }

		[InternalName("Corpo")]
		public String Corpo { get; set; }

		[InternalName("Fluxo")]
		public ListaSP_Fluxos Fluxo { get; set; }

		[InternalName("Destinatarios")]
		public List<Grupo> Destinatarios { get; set; }

		[InternalName("DestinatariosItem")]
		public String DestinatariosItem { get; set; }

		[InternalName("DestinatariosTodosAprovadores")]
		public Boolean? DestinatariosTodosAprovadores { get; set; }

		[InternalName("EnviarPdf")]
		public Boolean? EnviarPdf { get; set; }

		[InternalName("TipoTemplate")]
		public String TipoTemplate { get; set; }

	}
		
	[InternalName("Raízen - Aprovações Headline Size")]
	public class ListaSP_RaizenAprovacoesHeadlineSize : EntidadeSP
	{
		[InternalName("TipoAprovacao")]
		public String TipoDeAprovacao { get; set; }

		[InternalName("Grupo")]
		public Grupo Grupo { get; set; }

		[InternalName("ResponsavelItem")]
		public String ResponsavelItem { get; set; }

	}
		
	[InternalName("Headline Size - Financeiro")]
	public class ListaSP_HeadlineSizeFinanceiro : EntidadeSP
	{
		[InternalName("HeadlineInicial")]
		public Int32? HeadlineSizeInicial { get; set; }

		[InternalName("HeadlineFinal")]
		public Int32? HeadlineSizeFinal { get; set; }

		[InternalName("Aprovadores")]
		public List<ListaSP_RaizenAprovacoesHeadlineSize> Aprovadores { get; set; }

	}
		
	[InternalName("Headline Size - Planejamento")]
	public class ListaSP_HeadlineSizePlanejamento : EntidadeSP
	{
		[InternalName("HeadlineInicial")]
		public Int32? HeadlineSizeInicial { get; set; }

		[InternalName("HeadlineFinal")]
		public Int32? HeadlineSizeFinal { get; set; }

		[InternalName("Aprovadores")]
		public List<ListaSP_RaizenAprovacoesHeadlineSize> Aprovadores { get; set; }

	}
		
	[InternalName("Headline Size - Vendas")]
	public class ListaSP_HeadlineSizeVendas : EntidadeSP
	{
		[InternalName("HeadlineInicial")]
		public Int32? HeadlineSizeInicial { get; set; }

		[InternalName("HeadlineFinal")]
		public Int32? HeadlineSizeFinal { get; set; }

		[InternalName("Aprovadores")]
		public List<ListaSP_RaizenAprovacoesHeadlineSize> Aprovadores { get; set; }

	}
		
	[InternalName("Raizen Configurações")]
	public class ListaSP_RaizenConfiguracoes : EntidadeSP
	{
		[InternalName("Title")]
		public String Chave { get; set; }

		[InternalName("Valor")]
		public String Valor { get; set; }

	}
		
	[InternalName("Aprovação E-mail")]
	public class ListaSP_AprovacaoEmail : EntidadeSP
	{
		[InternalName("Saida")]
		public String[] Saida { get; set; }

	}
		
	[InternalName("TemplateForm")]
	public class ListaSP_TemplateForm : EntidadeSP
	{
		[InternalName("RazaoSocial")]
		public String RazaoSocial { get; set; }

		[InternalName("IBM")]
		public Int32? IBMValor { get; set; }

		[InternalName("SiteCode")]
		public Int32? SiteCodeValor { get; set; }

		[InternalName("EstadoAtualFluxo")]
		public String EstadoAtualDoFluxo { get; set; }

		[InternalName("BuscaDocumentos")]
		public Boolean? BuscaDeDocumentos { get; set; }

		[InternalName("ContratoPadrao")]
		public Boolean? ContratoPadrao { get; set; }

		[InternalName("GerenteTerritorio")]
		public Usuario GerenteDeTerritorio { get; set; }

		[InternalName("GerenteRegiao")]
		public Usuario GerenteDeRegiao { get; set; }

		[InternalName("DiretorVendas")]
		public Usuario DiretorDeVendas { get; set; }

		[InternalName("CDR")]
		public Usuario CDR { get; set; }

		[InternalName("GDR")]
		public Usuario GDR { get; set; }

		[InternalName("EtapaReprovada")]
		public String EtapaReprovada { get; set; }

		[InternalName("TarefasConcluidas")]
		public String TarefasConcluidas { get; set; }

		[InternalName("Etapa")]
		public String Fase { get; set; }

		[InternalName("UtilizaZoneamentoPadrao")]
		public Boolean? UtilizaZoneamentoPadrao { get; set; }

	}
		
}