//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnoContratual : EntidadeDB, IentidadeDBCore
    {
    	
        public int ID { get; set; }
    	
        public int IdProposta { get; set; }
    	
        public int IdTipoProposta { get; set; }
    	
        public Nullable<bool> CasoBase { get; set; }
    	
        public bool Ativo { get; set; }
    	
        public int Ano { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> Bonificacao { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> BonificacaoPorAno { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> CurvaMaturacaoVolumePadrao { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> CurvaMaturacaoVolumeExcecao { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> OutrasReceitas { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> OutrasDespesas { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> CurvaMaturacaoVolumes { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> OutrosFluxosPositivos { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> OutrosFluxosNegativos { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> Diesel { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> Otto { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> OleoCombustivel { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> Arla { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> CurvaMaturacaoFuels { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> AluguelPago { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> AluguelRecebido { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> Manutencao { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> MeioAmbiente { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> Terrenos { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> EdificacoesPista { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> EdificacoesLoja { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> Bombas { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> Tanques { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> ImagemRVI { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> EquipamentosLoja { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> CurvaMaturacaoLoja { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> Gasolina { get; set; }
    	
    	[Scale(5)]
        public Nullable<decimal> Etanol { get; set; }
    
        public virtual TipoProposta TipoProposta { get; set; }
    }
}
