//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento : EntidadeDB, IentidadeDBCore
    {
        public Documento()
        {
            this.PropostaDocumento = new HashSet<PropostaDocumento>();
            this.TipoPropostaDocumento = new HashSet<TipoPropostaDocumento>();
        }
    
    	
        public int IdDocumento { get; set; }
    	
        public string Nome { get; set; }
    	
        public string Agrupador { get; set; }
    
        public virtual ICollection<PropostaDocumento> PropostaDocumento { get; set; }
        public virtual ICollection<TipoPropostaDocumento> TipoPropostaDocumento { get; set; }
    }
}
