//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoSP : EntidadeDB, IentidadeDBCore
    {
        public GrupoSP()
        {
            this.GrupoUsuariosSP = new HashSet<GrupoUsuariosSP>();
        }
    
    	
        public int IdGrupoSP { get; set; }
    	
        public string Nome { get; set; }
    	
        public bool Ativo { get; set; }
    
        public virtual ICollection<GrupoUsuariosSP> GrupoUsuariosSP { get; set; }
    }
}
