//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lembrete : EntidadeDB, IentidadeDBCore
    {
    	
        public int IdLembrete { get; set; }
    	
        public int IdTarefa { get; set; }
    	
        public string EmailPara { get; set; }
    	
        public string LoginPara { get; set; }
    	
        public string NomePara { get; set; }
    	
        public System.DateTime DataEnvio { get; set; }
    	
        public bool CopiarSuperior { get; set; }
    	
        public bool EmailEnviado { get; set; }
    	
        public string DescricaoAssunto { get; set; }
    	
        public string DescricaoMensagem { get; set; }
    	
        public string LoginInclusao { get; set; }
    	
        public System.DateTime DataInclusao { get; set; }
    	
        public string LoginAlteracao { get; set; }
    	
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    	
        public bool Ativo { get; set; }
    
        public virtual Tarefa Tarefa { get; set; }
    }
}
