//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaHist : EntidadeDB, IentidadeDBCore
    {
    	
        public int IdListaHist { get; set; }
    	
        public System.Guid CodigoLista { get; set; }
    	
        public int CodigoItem { get; set; }
    	
        public string XmlAlteracao { get; set; }
    	
        public string LoginInclusao { get; set; }
    	
        public System.DateTime DataInclusao { get; set; }
    	
        public string LoginAlteracao { get; set; }
    	
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    	
        public bool Ativo { get; set; }
    
        public virtual Lista Lista { get; set; }
    }
}
