//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;

	public partial class Log : EntidadeDB, IentidadeDBCore
    {
    	
        public long IdLog { get; set; }
    	
        public string NomeProcesso { get; set; }
    	
        public string DescricaoOrigem { get; set; }
    	
        public string DescricaoMensagem { get; set; }
    	
        public string DescricaoDetalhe { get; set; }
    	
        public bool Erro { get; set; }
    	
        public string LoginInclusao { get; set; }
    	
        public System.DateTime DataInclusao { get; set; }
    }
}
