//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogIntegracao : EntidadeDB, IentidadeDBCore
    {
    	
        public long IdLogIntegracao { get; set; }
    	
        public System.DateTime DataExecucao { get; set; }
    	
        public int WorkflowProgressID { get; set; }
    	
        public int QuaNOTIFdadeLista { get; set; }
    	
        public int QuaNOTIFdadeInstancia { get; set; }
    	
        public int QuaNOTIFdadeTarefa { get; set; }
    	
        public int QuaNOTIFdadeDelegacao { get; set; }
    	
        public int TempoExecucao { get; set; }
    	
        public Nullable<bool> ExecucaoCompleta { get; set; }
    	
        public Nullable<bool> ExecucaoGestaoFluxo { get; set; }
    	
        public Nullable<int> QuaNOTIFdadeGestaoFluxoFluxo { get; set; }
    	
        public Nullable<int> QuaNOTIFdadeGestaoFluxoTarefa { get; set; }
    	
        public Nullable<int> QuaNOTIFdadeGestaoFluxoTarefaStatus { get; set; }
    }
}
