//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropostaDocumento : EntidadeDB, IentidadeDBCore
    {
    	
        public int IdPropostaDocumento { get; set; }
    	
        public int IdTipoProposta { get; set; }
    	
        public int IdDocumento { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual TipoProposta TipoProposta { get; set; }
    }
}
