//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFGestaoFluxo_Fluxo : EntidadeDB, IentidadeDBCore
    {
    	
        public int CD_SEQ_FLUXO { get; set; }
    	
        public int CD_ITEM { get; set; }
    	
        public System.Guid CD_LISTA { get; set; }
    	
        public string NM_LISTA { get; set; }
    	
        public string NM_SOLICITACAO { get; set; }
    	
        public string NM_IBM { get; set; }
    	
        public string NM_RAZAO_SOCIAL { get; set; }
    	
        public string NM_SOLICITANTE { get; set; }
    	
        public string NM_STATUS { get; set; }
    	
        public string NM_ATIVO { get; set; }
    	
        public string NM_GA { get; set; }
    	
        public string NM_GT { get; set; }
    	
        public Nullable<System.DateTime> DT_ENTRADA { get; set; }
    	
        public Nullable<System.DateTime> DT_SAIDA { get; set; }
    	
        public Nullable<System.DateTime> DT_CRIACAO { get; set; }
    	
        public Nullable<System.DateTime> DT_MODIFICACAO { get; set; }
    }
}
