
//------------------------------------------------------------------------------
// <auto-generated>
// Código Gerado via T4
//
// Não alterar o código - As informações serão perdidadas.
// </auto-generated>
//------------------------------------------------------------------------------
using PortalDeFluxos.Core.BLL.Atributos;
using System;
using System.Collections.Generic;
using Iteris;
using PortalDeFluxos.Core.BLL.Modelo;


namespace PortalDeFluxos.NOTIF.BLL.Modelo
{
		
	[InternalName("NOTIF")]
	public class ListaSP_NOTIF : EntidadePropostaSP
	{
		[InternalName("TipoNotificacao",FieldType.ReiniciarWF)]
		public String TipoNotificacao { get; set; }

		[InternalName("StatusLoja",FieldType.ReiniciarWF)]
		public String StatusLoja { get; set; }

		[InternalName("Consumo",FieldType.ReiniciarWF)]
		public String Consumo { get; set; }

		[InternalName("EnvolvimentoPlanejamento",FieldType.ReiniciarWF)]
		public Boolean? EnvolvimentoPlanejamento { get; set; }

		[InternalName("NotificacaoPadrao",FieldType.ReiniciarWF)]
		public Boolean? NotificacaoPadrao { get; set; }

		[InternalName("AprovacaoGRDV",FieldType.ReiniciarWF)]
		public Boolean? AprovacaoGRDV { get; set; }

		[InternalName("Farol",FieldType.ReiniciarWF)]
		public String Farol { get; set; }

		[InternalName("DataNotificacao",FieldType.ReiniciarWF)]
		public DateTime? DataDaNotificacao { get; set; }

	}
		
}