//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalDeFluxos.Core.BLL.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using PortalDeFluxos.NOTIF.BLL.Modelo;
    
    public partial class PortalDeFluxoEntities : DbContext
    {
    
        public virtual DbSet<ListaNOTIF> ListaNOTIF { get; set; }
        public virtual DbSet<ListaNOTIFNotificacoes> ListaNOTIFNotificacoes { get; set; }
    }
}
