//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;
using PortalDeFluxos.Core.BLL.Modelo;

namespace PortalDeFluxos.NOTIF.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    using PortalDeFluxos.Core.BLL.Core.Modelo;
    
    public partial class ListaNOTIFNotificacoes : EntidadeDB
    {
    	
        public int IdNotificacao { get; set; }
    	
        public int CodigoItem { get; set; }
    	
    	[MaxLength(255)]
        public string LoginInclusao { get; set; }
    	
        public System.DateTime DataInclusao { get; set; }
    	
    	[MaxLength(255)]
        public string LoginAlteracao { get; set; }
    	
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    	
        public bool Ativo { get; set; }
    	
        public bool NotifAtiva { get; set; }
    	
        public int NumeroNotificacao { get; set; }
    	
        public Nullable<int> Status { get; set; }
    	
    	[MaxLength(5000)]
        public string Observacao { get; set; }
    	
        public Nullable<System.DateTime> DataInicioContrato { get; set; }
    	
        public Nullable<System.DateTime> DataFimContrato { get; set; }
    	
        public Nullable<System.DateTime> DataNotificacao { get; set; }
    	
        public Nullable<bool> AprovacaoGRDV { get; set; }
    	
        public Nullable<bool> EnvolvimentoPlanejamento { get; set; }
    	
        public Nullable<int> GrauNotificacao { get; set; }
    	
    	[MaxLength(255)]
        public string FormaEnvio { get; set; }
    	
        public Nullable<bool> NotificacaoPadrao { get; set; }
    
        public virtual ListaNOTIF ListaNOTIF { get; set; }
    }
}
