//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Iteris;
using PortalDeFluxos.Core.BLL.Modelo;

namespace PortalDeFluxos.NOTIF.BLL.Modelo
{
    using System;
    using System.Collections.Generic;
    using PortalDeFluxos.Core.BLL.Core.Modelo;
    
    public partial class ListaNOTIF : EntidadeDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListaNOTIF()
        {
            this.ListaNOTIFNotificacoes = new HashSet<ListaNOTIFNotificacoes>();
        }
    
    	
        public int CodigoItem { get; set; }
    	
        public System.Guid CodigoLista { get; set; }
    	
    	[MaxLength(255)]
        public string LoginInclusao { get; set; }
    	
        public System.DateTime DataInclusao { get; set; }
    	
    	[MaxLength(255)]
        public string LoginAlteracao { get; set; }
    	
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    	
        public bool Ativo { get; set; }
    	
    	[MaxLength(255)]
        public string TituloProposta { get; set; }
    	
    	[MaxLength(255)]
        public string DescricaoRazaoSocial { get; set; }
    	
        public Nullable<int> NumeroIBM { get; set; }
    	
        public Nullable<int> NumeroSiteCode { get; set; }
    	
    	[MaxLength(255)]
        public string DescricaoEstadoAtualFluxo { get; set; }
    	
        public Nullable<bool> BuscaDocumentos { get; set; }
    	
        public Nullable<bool> ContratoPadrao { get; set; }
    	
    	[MaxLength(255)]
        public string DescricaoEtapa { get; set; }
    	
    	[MaxLength(255)]
        public string LoginGerenteTerritorio { get; set; }
    	
    	[MaxLength(255)]
        public string LoginGerenteRegiao { get; set; }
    	
    	[MaxLength(255)]
        public string LoginDiretorVendas { get; set; }
    	
    	[MaxLength(255)]
        public string LoginCDR { get; set; }
    	
    	[MaxLength(255)]
        public string LoginGDR { get; set; }
    	
        public Nullable<bool> UtilizaZoneamentoPadrao { get; set; }
    	
        public Nullable<bool> UtilizaZoneamentoCdr { get; set; }
    	
        public Nullable<bool> UtilizaZoneamentoDiretor { get; set; }
    	
        public Nullable<bool> UtilizaZoneamentoGdr { get; set; }
    	
        public Nullable<bool> UtilizaZoneamentoGR { get; set; }
    	
        public Nullable<bool> UtilizaZoneamentoGT { get; set; }
    	
        public Nullable<bool> EnvolvimentoPlanejamento { get; set; }
    	
        public Nullable<bool> AprovacaoGRDV { get; set; }
    	
        public Nullable<bool> NotificacaoPadrao { get; set; }
    	
        public Nullable<System.DateTime> DataNotificacao { get; set; }
    	
    	[MaxLength(50)]
        public string Farol { get; set; }
    	
        public Nullable<int> Mercado { get; set; }
    	
    	[MaxLength(18)]
        public string CNPJ { get; set; }
    	
    	[MaxLength(255)]
        public string Endereco { get; set; }
    	
    	[MaxLength(255)]
        public string Bairro { get; set; }
    	
    	[MaxLength(9)]
        public string Cep { get; set; }
    	
    	[MaxLength(255)]
        public string UF { get; set; }
    	
    	[MaxLength(255)]
        public string Cidade { get; set; }
    	
    	[MaxLength(255)]
        public string NomeContrato { get; set; }
    	
    	[MaxLength(255)]
        public string NumeroContrato { get; set; }
    	
        public Nullable<int> TipoNotificacao { get; set; }
    	
    	[MaxLength(255)]
        public string OutroTipoNotificacao { get; set; }
    	
    	[MaxLength(255)]
        public string StatusLoja { get; set; }
    	
    	[Scale(3)]
    	[Precision(15)]
        public Nullable<decimal> Consumo { get; set; }
    	
    	[MaxLength(5000)]
        public string Comentario { get; set; }
    	
        public Nullable<int> Juridico_FasesJudicializacao { get; set; }
    	
        public Nullable<int> Juridico_TipoAcaoJudicial { get; set; }
    	
    	[MaxLength(5000)]
        public string Juridico_Observacao { get; set; }
    	
        public Nullable<System.DateTime> Juridico_DataAcao { get; set; }
    	
    	[MaxLength(255)]
        public string RelacoesSetoriais_FaseDenuncia { get; set; }
    	
    	[MaxLength(255)]
        public string RelacoesSetoriais_OrgaoDenuncia { get; set; }
    	
    	[MaxLength(5000)]
        public string RelacoesSetoriais_Observacao { get; set; }
    	
        public Nullable<System.DateTime> RelacoesSetoriais_Data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaNOTIFNotificacoes> ListaNOTIFNotificacoes { get; set; }
    }
}
